In [2]:
# Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Found cached dataset csv (C:/Users/theim/.cache/huggingface/datasets/lukebarousse___csv/lukebarousse--data_jobs-20095235c13fb98d/0.0.0/6954658bab30a358235fa864b05cf819af0e179325c740e4bc853bcc7ec513e1)

  0%|          | 0/1 [00:00<?, ?it/s]

In [3]:
df_filtered_salary = df[pd.notna(df['salary_year_avg'])].copy()

In [4]:
def projected_salary(salary):
    return salary * 1.03

In [5]:
df_filtered_salary['projected_salary_year'] = df_filtered_salary['salary_year_avg'].apply(projected_salary)

In [6]:
df_filtered_salary['salary_inflated'] = df_filtered_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

In [7]:
df_filtered_salary[['salary_year_avg', 'projected_salary_year', 'salary_inflated']]

        salary_year_avg  projected_salary_year  salary_inflated
28             109500.0              112785.00        112785.00
77             140000.0              144200.00        144200.00
92             120000.0              123600.00        123600.00
100            228222.0              235068.66        235068.66
109             89000.0               91670.00         91670.00
...                 ...                    ...              ...
785624         139216.0              143392.48        143392.48
785641         150000.0              154500.00        154500.00
785648         221875.0              228531.25        228531.25
785682         157500.0              162225.00        162225.00
785692         157500.0              162225.00        162225.00

[22003 rows x 3 columns]

In [8]:
import ast

ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [9]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills'] =  df['job_skills'].apply(clean_list)

In [45]:
df['job_skills'] =  df['job_skills'].apply(lambda skill_list: ast
                                           .literal_eval(skill_list) 
                                           if pd.notna(skill_list) else skill_list)

In [11]:
def projected_inflation(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

In [12]:
df_filtered_salary['salary_inflated'] = df_filtered_salary.apply(projected_inflation, axis=1)

In [16]:
df_filtered_salary[['job_title_short', 'salary_year_avg', 'salary_inflated']].sample(20)

                  job_title_short  salary_year_avg  salary_inflated
116361              Data Engineer    121200.000000    124836.000000
193567  Machine Learning Engineer     89100.000000     91773.000000
764035           Business Analyst    110000.000000    113300.000000
246666               Data Analyst    111175.000000    114510.250000
81382               Data Engineer    175000.000000    180250.000000
518383               Data Analyst    111175.000000    114510.250000
624030             Data Scientist    100000.000000    103000.000000
663198      Senior Data Scientist    375000.000000    393750.000000
33164              Data Scientist    281450.500000    289894.015000
732281             Data Scientist    212000.000000    218360.000000
465027               Data Analyst     82500.000000     84975.000000
545664        Senior Data Analyst    111175.000000    116733.750000
498638      Senior Data Scientist    157500.000000    165375.000000
133913             Data Scientist    105151.500000    108306.045000
376697               Data Analyst     90612.601562     93330.979609
613215             Data Scientist     65000.000000     66950.000000
729992             Data Scientist    165000.000000    169950.000000
656366      Senior Data Scientist     79200.000000     83160.000000
212737           Business Analyst     95000.000000     97850.000000
535797              Data Engineer    144500.000000    148835.000000

In [17]:
# Lambda Function Version
df_filtered_salary['salary_year_inflated'] = df_filtered_salary.apply(
    lambda row: 1.05 * row['salary_year_avg'] if 'Senior' in row['job_title_short']
    else 1.03 * row['salary_year_avg'],
    axis=1
)

In [18]:
df_filtered_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].sample(20)

              job_title_short  salary_year_avg  salary_year_inflated
621572   Senior Data Engineer      145000.0000         152250.000000
165010  Senior Data Scientist      155000.0000         162750.000000
12401          Data Scientist      162500.0000         167375.000000
725815          Data Engineer      133000.0000         136990.000000
623908         Data Scientist      125000.0000         128750.000000
7118           Data Scientist      167500.0000         172525.000000
560024         Data Scientist      271500.0000         279645.000000
506686         Data Scientist      115000.0000         118450.000000
38393        Business Analyst       64800.0000          66744.000000
537944         Data Scientist      125814.0000         129588.420000
592790         Data Scientist       80000.0000          82400.000000
619521          Data Engineer      162500.0000         167375.000000
727158           Data Analyst       87500.0000          90125.000000
703189          Data Engineer      139216.0000         143392.480000
755974         Data Scientist      267875.0000         275911.250000
269343      Software Engineer      138000.0000         142140.000000
376329           Data Analyst       57500.0000          59225.000000
175881           Data Analyst       50000.0000          51500.000000
600352         Data Scientist      125000.4375         128750.450625
163250   Senior Data Engineer      152433.5000         160055.175000